#!/bin/bash
# Script for installing po-util for Travis CI
# bash <(curl -sL https://raw.githubusercontent.com/nrobinson2000/po/master/ci/ci-install)

sudo apt install -y expect

sudo curl -fsSLo /usr/local/share/po-common https://raw.githubusercontent.com/nrobinson2000/po/master/share/po-common
sudo curl -fsSLo /usr/local/share/po-linux https://raw.githubusercontent.com/nrobinson2000/po/master/share/po-linux
sudo curl -fsSLo /usr/local/bin/po https://raw.githubusercontent.com/nrobinson2000/po/master/bin/po
sudo chmod +x /usr/local/bin/po

curl -sLO https://raw.githubusercontent.com/nrobinson2000/po/master/ci/config-expect
chmod +x config-expect

./config-expect

po install ~/.po-util basic
